sudo: required
services:
  - docker

before_install:
  - docker build -t udemydockerid/docker-study -f Dockerfile.dev .

script:
  - docker run udemydockerid/docker-study

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-583153984007"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"