FROM alpine

RUN apk add --update maven
RUN apk update
RUN apk fetch openjdk8
RUN apk add openjdk8
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"

WORKDIR '/app'

COPY . .

CMD ["mvn", "clean", "test", "package"]
